import "./globals.css";
import "../../env";

export const metadata = {
  title: "Practice",
  description: "Generated By Alireza Abedi",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa">
      <body>{children}</body>
    </html>
  );
}
