import localFont from "next/font/local";

import "./globals.css";
import "../../env";

import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Messenger",
  description: "Generated By Alireza Abedi",
};

const myFont = localFont({
  src: "../assets/fonts/BYekan.woff2",
  display: "swap",
  variable: "--var-yekan-font",
});

export default async function RootLayout(props: any) {
  return (
    <html lang="fa">
      <body
        dir="rtl"
        className={`${myFont.variable} bg-zinc-800 overflow-hidden`}
      >
        <Toaster
          position="top-center"
          reverseOrder={false}
          toastOptions={{
            style: {
              borderRadius: "17px",
              background: "#333",
              color: "#fff",
            },
          }}
        />
        {props.children}
      </body>
    </html>
  );
}
